{% if request.lang == 'pt' %}
<h4>Informação</h4>
<p>INterface de PUblicação de Tesauro do LASeD (INPUT-LASeD) é uma plataforma web para publicação de tesauros gerenciado pelo grupo de pesquisa LASeD da Universidade Estadual do Paraná. Essa plataforma utiliza a interface Skosmos para possibilitar uma melhor interação do usuários.</p>
{% elseif request.lang == 'pt-BR' %}
<h4>Informação</h4>
<p>INterface de PUblicação de Tesauro do LASeD (INPUT-LASeD) é uma plataforma web para publicação de tesauros gerenciado pelo grupo de pesquisa LASeD da Universidade Estadual do Paraná. Essa plataforma utiliza a interface Skosmos para possibilitar uma melhor interação do usuários.;</p>
{% elseif request.lang == 'en' %}
<h4>About</h4>
<p>LASeD Thesaurus publishing interface (INPUT-LASeD) is a web platform for publishing thesauruses managed by the LASeD research group at theMidwestern State University (Brazil). This platform uses the Skosmos interface to enable better user interaction.</p>
{% endif %}
